name: smartini
channels:
 - conda-forge
dependencies:
 - python=3.12
 - openmm
 - openmmforcefields
 - openff-toolkit
 - openff-interchange
 - numpy
 - rdkit
 - mdanalysis
 - requests
 - pyyaml
 - lxml
 - beautifulsoup4
#  - matplotlib
#  - scikit-learn